### PR TITLE
Add PackageReferences

### PR DESCRIPTION
**Pull request by mholo65**
- Add property for quickly accessing package references.

### CODE REVIEW

**Comment by daveaglick** [comment]
Thanks!

In general not a huge fan of exposing tuples as return values from a public API.

Do any of these alternatives sound better to you:
* `IEnumerable<PackageReference>` (a new struct with `Package` and `Version` properties)
* `IEnumerable<KeyValuePair<string, string>>`
* `IReadOnlyDictionary<string, string>` (key = package name, value = version)

I think I like returning a dictionary for this, but could be talked into something else.

BTW - hopefully CI will light up green on next trigger. Been working on that, but don't worry about it if it's still red.

**Comment by mholo65** [comment]
I like the first one best:
> IEnumerable<PackageReference> (a new struct with Package and Version properties)

I'll update the PR.

**Comment by mholo65** [comment]
Sorry, was to quick on the "Comment" button 😄 Dictionary also has it advantages, and would be possible to add other properties dynamically. I think I'll lean into that.

**Comment by daveaglick** [comment]
Went ahead and merged this - changed it to a `IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>>` so that you can find package references by package ID but also get all the metadata including version.

**Pull request merged**
