### PR TITLE
Add support for update property

### LINKED ISSUE #170: PackageReference can contain name of package in Update instead of Include
Came across this researching https://github.com/eNeRGy164/LivingDocumentation/issues/37.

It seems you can use
```xml
<ItemGroup>
    <PackageReference Update="Microsoft.NETCore.App" Version="2.1.0" />
</ItemGroup>
```

and Buidalyzer currently only support 

```xml
<ItemGroup>
    <PackageReference Include="Microsoft.NETCore.App" Version="2.1.0" />
</ItemGroup>
```

to get the name.

### PR DESCRIPTION
**Pull request by eNeRGy164**
If `Include` is not set, try `Update`

Fixes #170

### CODE REVIEW

**Comment by eNeRGy164** [comment]
Hi @daveaglick,

Any chance you will have some time to look at the PR's?

**Comment by daveaglick** [comment]
Probably not this week (I'm on vacation and try hard to unplug), but I'll definitely carve out time early next week when I'm back. Got a few projects with backed up PRs to look at.

**Comment by eNeRGy164** [comment]
No problem, enjoy your vacation!

**Comment by eNeRGy164** [comment]
*\*poke\**

@daveaglick, consider this a friendly nudge :)

**Comment by daveaglick** [comment]
Guess it's **finally** time I clear the backlog here :) I'll start going through the open PRs and merging them with a release once they're all done.

**Comment by daveaglick** [comment]
And merged! Thanks...and especially for including some tests that make this easy to hit the merge button :). I'll get a release out ASAP once I clear the rest of the backlog.

**Pull request merged**
