### PR TITLE
Add interfaces

### LINKED ISSUE #102: Unit testing with Buildalyzer
## Introduction
Hi, I'm using Buildalyzer in [Stryker.NET](https://github.com/stryker-mutator/stryker-net). The implementation is great and solves a lot of our problems with analyzing .net core projects. But I'm having trouble with writing good unit tests for the parts that use buildalyzer output.

## Issue
In our unit tests we can't mock/instantiate AnalyzerResult objects. Troughout our whole application we need to have this objects available. If all unit tests have to analyze a whole project to get a AnalyzerResult object to only read one property, our unit tests will get overly complicated for a seemingly easy task.

For example:
``` csharp
var testProjectAnalyzerResultMock = new Mock<AnalyzerResult>(MockBehavior.Strict);
var mockedBuildalyzerResult = testProjectAnalyzerResultMock.Object;
```
Throws an exception since AnalyserResult doesn't expose an parameterless constructor. It would be great if mocking AnalyzerResults was possible. 

## Request
Define interfaces for all public classes like `AnalyzerResult`, `AnalyzerManager` and `ProjectAnalyzer`. Also make sure a parameterless constructor is available and `public`.

### PR DESCRIPTION
**Pull request by richardwerkman**
This PR adds interfaces to the classes I would like to be able to mock for unit testing perposes.

closes #102

### CODE REVIEW

**Comment by richardwerkman** [comment]
@daveaglick could you take a look at this?

**Comment by daveaglick** [comment]
Thanks a bunch for the PR! Yep, happy to take a look at it as soon as I get the chance. It'll likely be early(ish) next week before I'm able to merge it in and get a new release out, but at first glance the changes look good. Always happy to make testing easier :)

**Comment by richardwerkman** [comment]
Cool, looking forward to be able to unit test with buildalyzer 😃 

I've tried it without the interfaces but it was just such a pain in the ass. This will make testing a lot easier! Thanks for wanting to release as soon as possible 👍

**Comment by richardwerkman** [comment]
Ping

**Comment by daveaglick** [comment]
Sorry for the delay, took me longer than I thought to find some time to run all the unit tests and verify everything. Looks great, thanks for the excellent work. Merging now and will release to NuGet right after.

**Pull request merged**
